#!/usr/bin/node
const express = require('express');
const app = express();
const port = 3333;

app.use(express.json());

app.post('/', async (req, res) => {
  const requestData = req.body;
  console.log(JSON.stringify(requestData))
  res.status(200).json({ message: 'success post' })
});
app.get('/', async (req, res) => {
  res.status(200).json({ message: 'success get' })
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
